version: '3.8'

services:
  app:
    image: url_shortener
    depends_on:
      - mongo
    build: .
    restart: always
    ports:
      - 5000:${PORT}
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - COOKIE_KEY=${COOKIE_KEY}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}